name: Release Tampermonkey Userscript

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-attach:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update version in src/index.js
        id: version_update
        run: |
          VERSION=${{ github.event.release.tag_name }}
          sed -i -E "s#(@version\\s+).*#\\1$VERSION#" src/index.js || true

      - name: Build Tampermonkey userscript
        run: |
          mkdir -p output
          ./build-tampermonkey.sh

      - name: Commit and push version change
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/index.js
          git commit -m "chore: update userscript version to ${{ github.event.release.tag_name }} for release ${{ github.event.release.tag_name }}" || echo "No changes to commit"
          git push origin HEAD:${{ github.event.repository.default_branch }}

      - name: Upload userscript as release asset
        uses: softprops/action-gh-release@v2
        with:
          files: output/github-actions-dashboard.user.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
